name             'my_cookbook'
maintainer       'ByteKinetic'
maintainer_email 'btreece@bytekinetic.com'
license          'Apache 2.0'
description      'Installs/Configures my_cookbook'
issues_url	 ''
source_url	 ''
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'

depends 'build-essential'
depends 'chef-client'
depends 'apt'
depends 'ntp'
depends 'apache2', '>= 3.2.2'
conflicts 'nginx'
