---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  data_bags_path: 'test/fixtures/data_bags'

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
    driver:
      provider: parallels

suites:
  - name: default
    driver:
      vm_hostname: sensu-master.hivltg.net
      customize:
        memory: 512
        cpus: 1
    data_bags_path: 'test/fixtures/data_bags'
    run_list:
      - recipe[apt::default]
      - recipe[sensu_server::default]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
      sensu_server: {
        influxdb_address: '192.168.1.6',
        influxdb_port: 8090
      }
