name 'sensu_server'
maintainer 'ByteKinetic'
maintainer_email 'btreece@bytekinetic.com'
license 'all_rights'
description 'Installs/Configures sensu_server'
long_description 'Installs/Configures sensu_server'
version '0.1.5'

depends 'sensu'
depends 'uchiwa'
