name 'log_agent'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures td-agent'
long_description 'Installs/Configures td-agent'
version '0.1.1'

depends 'td-agent'
depends 'rsyslog'
